import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "../../public/fonts/font";
import ClientWrapper from "@/components/client-wrapper";
import Footer from "@/components/footer";
import { Toaster } from "sonner";
import dynamic from "next/dynamic";

// Importación dinámica del modal para evitar problemas de hidratación
// const WelcomeModal = dynamic(() => import("@/components/modals/WelcomeModal"), {
//   ssr: false,
// });

export const metadata: Metadata = {
  title: "CSalud",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/meta-icon-alivio.png",
    shortcut: "/icons/meta-icon-alivio.png",
    apple: "/icons/meta-icon-alivio.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <ClientWrapper>
          <main className="antialiased">
            {/* <WelcomeModal /> */}
            {children}
          </main>
          <Footer />
        </ClientWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
