import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "../../public/fonts/font";
import ClientWrapper from "@/components/client-wrapper";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "CSalud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <ClientWrapper>
          <main className="antialiased">
            {children}
          </main>
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
