import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "../../public/fonts/font";
import ClientWrapper from "@/components/client-wrapper";
import Footer from "@/components/footer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "CSalud",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/meta-icon-alivio.png",
    shortcut: "/icons/meta-icon-alivio.png",
    apple: "/icons/meta-icon-alivio.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <ClientWrapper>
          <main className="antialiased">{children}</main>
          <Footer />
        </ClientWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
